typography_spectrum: 0.5425228457897902
color:
  brandStrength: 0.7474861985538155
  lightness: 0.25511671928688884
  saturation: 0.8695006901398301
  rhythmicContrast: 0.0033133667893707752
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.11217959155328572
name: wor(l)dtravel
navigation:
  - name: About Me
    url: /aboutme
    type: external
  - name: Stuff I Like
    url: /stuff-i-like
    type: external
title: Wor(l)dtravel
description: Eine schöne Testseite
