typography_spectrum: 0.5966484018135816
color:
  brandStrength: 0.3638083229307085
  lightness: 0.47901969333179295
  saturation: 0.8156319232657552
  rhythmicContrast: 0.9055619882419705
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
layout_spectrum: 0.19770681066438556
name: wor(l)dtravel
navigation:
  - name: About Me
    url: /aboutme
    type: external
  - name: Stuff I Like
    url: /stuff-i-like
    type: external
title: Wor(l)dtravel
description: Eine schöne Testseite
